### ISSUE TITLE
Survivorship bias

### ISSUE THREAD

**Issue by KobusViljoen** [KobusViljoen/Thesis#5]
Have a look at the tickers from 2001 up to 2016, using the equity screen

**Comment by KobusViljoen** [comment]
At the moment, the total number of shares are 700, go back to bloomberg and make sure all of them are active

**Comment by KobusViljoen** [comment]
when I have a look at the data from 2002, there is a slight improvement. The number of shares extracted using the equity screen varies between 159 and 165

**Comment by KobusViljoen** [comment]
A good choice may be to choose the first rebalancing data as 2002-03-28. A bit of data snooping taking place here

**Comment by csrvermaak** [comment]
@KobusViljoen : 100% Agree - use data from 2002 :)

**Comment by csrvermaak** [comment]
(Nice usage of Issues btw 👍 )

**Comment by KobusViljoen** [comment]
This is therefore sorted
