### ISSUE TITLE
Stock selection for single factor portfolios

### ISSUE THREAD

**Issue by KobusViljoen** [KobusViljoen/Thesis#6]
When I apply the stock selection process for the single factor portfolios, to many stocks filter through except for the quality model and 4 factor model. The single factor portfolios struggles to outperform the benchmark.

Should I consider selecting the stocks above a higher quantile or should I impose a trading volume filter as well??

The new stock selection process will be uploaded shortly, this process uses cross sectional comparisons.

**Comment by csrvermaak** [comment]
I'm not sure I follow?

> to many stocks filter through except for the quality model and 4 factor model.

**Comment by KobusViljoen** [comment]
When I use the Momentum (1 yr returns), Value (Earnings yield) or Volatility (60D SD) model,  between 50 and 75 stocks get selected each quarter. This is based on selecting the top 50% of the stocks, given their z-score. I'm not sure if that amount of shares are to much or if I have to use a higher quantile.

**Comment by csrvermaak** [comment]
You should have >30 stocks for a diversified portfolio, thus you could maybe use the top 40%.

**Comment by KobusViljoen** [comment]
Okay I'll try that now, I believe my final code will be ready and uploaded by Sunday.
For the Quality (Gross Profit) and 4 Factor model I also need to adjust the quantile, due to not enough stocks filtering through (between 17 en 23). I'll test the thresholds.
